src/Shann/ItemBundle/Entity/Item.php
<?php

namespace Shann\ItemBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Item
 *
 * @ORM\Table(name="item")
 * @ORM\Entity(repositoryClass="Shann\ItemBundle\Repository\ItemRepository")
 */
class Item
{
    const DEFAULT_IMAGE = 'http://via.placeholder.com/250x250?text=No+image';

    const STATUS_ACTIVE     = 1;
    const STATUS_DRAFT      = 2;
    const STATUS_RECEIVED   = 3;
    const STATUS_GIVEN      = 4;

    public function __construct()
    {
        $this->createdAt = new \Datetime();
    }

    public static function getStatusNames()
    {
        return [
            self::STATUS_ACTIVE => 'Active',
            self::STATUS_DRAFT  => 'Draft',
        ];
    }

    public function getStatusName($id = 0)
    {
        if (intval($id)) {
            return self::getStatusNames()[$id];
        }
        return null;
    }

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="ItemImage", mappedBy="item", cascade={"persist", "remove"})
     */
    private $images;

    /**
     * @ORM\Column(name="status", type="integer")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="Shann\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="recipient", referencedColumnName="id")
     */
    private $recipient;

    /**
     * @ORM\ManyToOne(targetEntity="Shann\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="user", referencedColumnName="id")
     */
    private $user;

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(name="date_given", type="datetime", nullable=true)
     */
    private $dateGiven;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Item
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set status
     *
     * @param integer $status
     *
     * @return Item
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Item
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set recipient
     *
     * @param \Shann\UserBundle\Entity\User $recipient
     *
     * @return Item
     */
    public function setRecipient(\Shann\UserBundle\Entity\User $recipient = null)
    {
        $this->recipient = $recipient;

        return $this;
    }

    /**
     * Get recipient
     *
     * @return \Shann\UserBundle\Entity\User
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * Set user
     *
     * @param \Shann\UserBundle\Entity\User $user
     *
     * @return Item
     */
    public function setUser(\Shann\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \Shann\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Add image
     *
     * @param \Shann\ItemBundle\Entity\ItemImage $image
     *
     * @return Item
     */
    public function addImage(\Shann\ItemBundle\Entity\ItemImage $image)
    {
        $this->images[] = $image;

        return $this;
    }

    /**
     * Remove image
     *
     * @param \Shann\ItemBundle\Entity\ItemImage $image
     */
    public function removeImage(\Shann\ItemBundle\Entity\ItemImage $image)
    {
        $this->images->removeElement($image);
    }

    /**
     * Get images
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getImages()
    {
        return $this->images;
    }


    static $imagePath = null;

    public static function setPaths($filepaths, $userId)
    {
        if ($filepaths) {
            self::$imagePath =  $filepaths['item_image'] . $userId;
        }
    }

    public function getImageThumb()
    {
        if (count($this->images) > 0) {
            return self::$imagePath . '/' . $this->images->first()->getThumb();
        }
       return null;
    }

    public function imagePath()
    {
        if (count($this->images) > 0) {
            return self::$imagePath . '/';
        }
        return null;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Item
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set dateGiven
     *
     * @param \DateTime $dateGiven
     *
     * @return Item
     */
    public function setDateGiven($dateGiven)
    {
        $this->dateGiven = $dateGiven;

        return $this;
    }

    /**
     * Get dateGiven
     *
     * @return \DateTime
     */
    public function getDateGiven()
    {
        return $this->dateGiven;
    }
}

src/Shann/ItemBundle/Entity/ItemImage.php
<?php

namespace Shann\ItemBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ItemImage
 *
 * @ORM\Table(name="item_image")
 * @ORM\Entity(repositoryClass="Shann\ItemBundle\Repository\ItemImageRepository")
 */
class ItemImage
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="original_name", type="string", length=255, nullable=true)
     */
    private $originalName;

    /**
     * @ORM\Column(name="filename", type="string", length=255)
     */
    private $filename;

    /**
     * @ORM\Column(name="thumb", type="string", length=255)
     */
    private $thumb;

    /**
     * @ORM\ManyToOne(targetEntity="Item")
     * @ORM\JoinColumn(name="item", referencedColumnName="id")
     */
    private $item;

    /**
     * @ORM\ManyToOne(targetEntity="Shann\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="user", referencedColumnName="id")
     */
    private $user;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set item
     *
     * @param \Shann\ItemBundle\Entity\Item $item
     *
     * @return ItemImage
     */
    public function setItem(\Shann\ItemBundle\Entity\Item $item = null)
    {
        $this->item = $item;

        return $this;
    }

    /**
     * Get item
     *
     * @return \Shann\ItemBundle\Entity\Item
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Set user
     *
     * @param \Shann\UserBundle\Entity\User $user
     *
     * @return ItemImage
     */
    public function setUser(\Shann\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \Shann\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set filename
     *
     * @param string $filename
     *
     * @return ItemImage
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * Get filename
     *
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set thumb
     *
     * @param string $thumb
     *
     * @return ItemImage
     */
    public function setThumb($thumb)
    {
        $this->thumb = $thumb;

        return $this;
    }

    /**
     * Get thumb
     *
     * @return string
     */
    public function getThumb()
    {
        return $this->thumb;
    }

    /**
     * Set originalName
     *
     * @param string $originalName
     *
     * @return ItemImage
     */
    public function setOriginalName($originalName)
    {
        $this->originalName = $originalName;

        return $this;
    }

    /**
     * Get originalName
     *
     * @return string
     */
    public function getOriginalName()
    {
        return $this->originalName;
    }

    public function getImageThumb()
    {
        if ($this->thumb !== null) {
            return '/uploads/' . $this->getUser()->getId() . '/' . $this->thumb;
        }

        return null;
    }

    public function getWideImage()
    {
        if ($this->filename !== null) {
            return '/uploads/' . $this->getUser()->getId() . '/' . $this->filename;
        }
        
        return null;
    }
}

src/Shann/ItemBundle/Form/ItemType.php
<?php

namespace Shann\ItemBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

use Shann\ItemBundle\Entity\Item;

class ItemType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, array(
                'label'         => 'Item Name',
                'label_attr'    => array(
                    'class'     => 'control-label'
                ),
                'attr'          => array(
                    'placeholder'   => 'Enter item name',
                    'class'     => 'form-control',
                    'type'      => 'text',
                    'required'  => true
                )
            ))
            ->add('description', TextareaType::class, array(
                'label'         => 'Item Description',
                'attr'          => array(
                    'class'     => 'form-control',
                    'rows'      => '10'
                )
            ))
            ->add('photos', FileType::class, array(
                'label'         => false,
                'required'      => false,
                'mapped'        => false,
                'attr'          => array(
                    'class'     => 'hidden'
                ),
                'multiple'      => true
            ))
            ->add('status', ChoiceType::class, array(
                'multiple'      => false,
                'expanded'      => false,
                'label'         => 'Item Status',
                'label_attr'    => array(
                    'class'     => 'control-label'
                ),
                'choices'       => array_flip(Item::getStatusNames()),
                'attr'          => array(
                    'data-style'=> 'btn btn-block btn-block',
                    'class'     => 'selectpicker',
                )
            ))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Shann\ItemBundle\Entity\Item'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'shann_itembundle_item';
    }


}

src/Shann/ItemBundle/Controller/Item/ItemController.php
<?php

/**
 * Display Public Items
 */
namespace Shann\ItemBundle\Controller\Item;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\HttpFoundation\JsonResponse;

use Intervention\Image\ImageManagerStatic as Image;

use Shann\UserBundle\Entity\User;
use Shann\ItemBundle\Entity\Item;
use Shann\ItemBundle\Entity\ItemImage;
use Shann\ItemBundle\Form\ItemType;

class ItemController extends \Shann\UserBundle\Controller\CoreController
{
    const PARENT_ROUTE = 'browse';

    public function browseAction(Request $request)
    {
        
        $em = $this->em();
        
        $items = $em->getRepository('ShannItemBundle:Item')->findLatest();

        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $items, 
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('ShannItemBundle:Item:index.html.twig', array(
            'items'             => $items,
            'title'             => 'Items',
            'pagination'        => $pagination,
            'route'             => [
               'parentRoute'    => self::PARENT_ROUTE,
                'childRoute'    => $this->route($request),
            ],
        ));
    }
}

src/Shann/ItemBundle/Resources/views/Item/index.html.twig
{# For public items #}
{% extends 'template/base.html.twig' %}

{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{{ asset('libs/slimbox/css/slimbox2.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('libs/izimodal/css/iziModal.min.css') }}">
{% endblock %}

{% block pageTitle %}{{ title }}{% endblock %}

{% block  mainContent %}
	<div class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">

					{% if app.session.flashBag.has('success') %}
						<div class="alert alert-success">
							{% for msg in app.session.flashBag.get('success') %}
								{{ msg }}
							{% endfor %}
						</div>
					{% endif %}

                    <div class="card">
                        <div class="card-header">
                        	<h4 class="card-title">Latest Items</h4>
                            <p class="category">A list of latest free items</p>
                            <hr>
                        </div>
                        <div class="card-content">

                        	{% if pagination.getTotalItemCount %}
	                        		<div class="row">
                        		{% for item in pagination %}
										<div class="col-sm-6 col-md-4">
											<div class="thumbnail">
												{% for img in item.images %}
													{% if loop.index == 1 %}
														<a href="{{ img.wideImage }}" rel="lightbox-item{{ item.id }}">
															<img src="{{ img.imageThumb }}" alt="...">
														</a>
													{% else %}
														<a href="{{ img.wideImage }}"  rel="lightbox-item{{ item.id }}" class="hidden">
															<img src="{{ img.imageThumb }}" alt="...">
														</a>
													{% endif %}
													{% if loop.last %}
														<span class="label label-warning item-image-total">{{ item.images|length }}</span>
														<div class="caption">
															<div class="caption-title">
																<strong>{{ item.name|truncate(80) }}</strong>
															</div>
															<p>
																<a href="#" class="btn btn-danger" role="button"><i class="fa fa-heart"></i></a> 
																<a href="#" class="btn btn-success sendMsg" 
																	data-id="{{ item.id }}" 
																	data-userid="{{ item.user.id }}"
																	data-firstname="{{ item.user.firstname }}"
																	data-itemname="{{ item.name }}"
																	role="button"><i class="fa fa-comment"></i></a>
															</p>
														</div>
													{% endif %}
												{% endfor %}
											</div>
										</div>
								{% endfor %}
									</div>
	                        {% else %}
	                        	<div class="text-danger">There are no active items yet.  Please try again later.</div>
	                        {% endif %}
						</div>
                    </div>
                </div>
			</div>
		</div>
	</div>

{% endblock %}

{% block modals %}
	<div id="modalMessage">
		<div class="message-box">
			<form id="messageForm" class="text-right">
				<div class="form-group">
					<p class="text-left">
						<label>Type your message below</label>
					</p>
					<textarea name="message" id="messageContent" class="form-control" rows="5"></textarea>
				</div>
				<div class="form-group">
					<p class="text-right">
							<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
							<button id="sendMyMessage" class="btn btn-success" type="submit"><i class="fa fa-main-forward"></i> Send Message</button>
					</p>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	<script type="text/javascript" src="{{ asset('libs/slimbox/js/slimbox2.js') }}"></script>
	<script type="text/javascript" src="{{ asset('libs/izimodal/js/iziModal.min.js') }}"></script>
	<script type="text/javascript">
		$(function() {
			
			var modalMessage 	= $('#modalMessage'),
				sendMsg      	= $('.sendMsg'),
				sendMyMessage	= $('#sendMyMessage'),
				recipientName 	= null,
				postItemId 		= 0,
				recipientId 	= 0;

			modalMessage.iziModal({
				icon 	: 'fa fa-comments'
			});

			sendMsg.click(function(e) {

				var content = $('#messageContent');
				content.val('');

				var userId    = $(this).data('userid'),
					firstname = $(this).data('firstname'),
					itemname  = $(this).data('itemname'),
					itemId 	  = $(this).data('id');

				modalMessage.iziModal('setTitle', 'Send message to : '+ firstname);
				modalMessage.iziModal('setSubtitle', 'Item : ' + itemname);

				recipientName 		= firstname;
				recipientId 		= userId;
				postItemId 			= itemId;

				modalMessage.iziModal('open');
			});

			$('#messageForm').submit(function(e) {
				e.preventDefault();

				swal({
					title 				: "Sending message!",
					imageUrl 			: "{{ asset('img/loader.gif') }}",
					showConfirmButton 	: false,
					showCancelButton 	: true
				});

				var content = $(this).find('#messageContent').val();

				if (content == '') {
					swal({
						title 		: 'Message Empty!',
						text 		: 'Please write something..',
						type 		: 'error'
					});

					return false;
				}

				$.post("{{ path('message_new') }}", {recipientid:recipientId,itemid:postItemId,msg:content}, function(data) {
					swal({
						title 		: data.title,
						text 		: data.text,
						type 		: data.error ? 'error' : 'success',
						html 		: true
					}, function(e) {
						if (data.success) {
							modalMessage.iziModal('close');
						}
					});
				})
				.fail(function(xhr, status, response) {
					
				});
			});

		});
	</script>
{% endblock %}